version: "3.8"

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-testingUA
    restart: always
    environment:
      POSTGRES_DB: testingUA
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: nguyentanthanh0709/testing-spring-boot-app:1.0
    container_name: testing-spring-boot-app
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: stg
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/testingUA
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres-db

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    depends_on:
      - postgres-db

volumes:
  postgres_data:
  jenkins_home:
